"use client";
import { Check, MessageCircle, Minus, Plus, Share2, ShieldCheck, Sparkles, Zap } from "lucide-react";
import { useState } from "react";
import type { Product } from "@/lib/storefront/types";
import { createWhatsAppOrderLink } from "@/lib/whatsapp/order-link";
import { Price } from "@/components/ui/Price";
import { Stars } from "@/components/ui/Stars";
import { useCart } from "@/components/cart/CartProvider";
import { kuStringColors, type KuStringColor } from "@/lib/cart/types";

const colorLabel = (color: KuStringColor) => color[0].toUpperCase() + color.slice(1);

export function PurchasePanel({ product }: { product: Product }) {
  const [bundle, setBundle] = useState(product.bundles.find((item) => item.id === "pick-any-two") ?? product.bundles[0]);
  const [quantity, setQuantity] = useState(bundle.quantity);
  const [colors, setColors] = useState<[KuStringColor, KuStringColor]>(["blue", "pink"]);
  const [message, setMessage] = useState("");
  const { addItem } = useCart();
  const choose = (id: string) => { const next = product.bundles.find((item) => item.id === id)!; setBundle(next); setQuantity(next.quantity); };
  const selectedColors = bundle.id === "pick-any-two" ? colors : undefined;
  const bundleLabel = selectedColors ? `${bundle.label} (${selectedColors.map(colorLabel).join(" + ")})` : bundle.label;
  const productImage = product.media.find((item) => item.type === "image")?.src ?? product.media[0].poster ?? product.media[0].src;
  const add = () => { addItem({ productId: product.id, name: product.name, image: productImage, unitPrice: bundle.unitPrice, quantity, bundleId: bundle.id, bundleQuantity: bundle.quantity, ...(selectedColors ? { colors: selectedColors } : {}) }); setMessage(`${product.name} added to your bag.`); };
  const whatsappLink = createWhatsAppOrderLink({ productName: product.name, bundleLabel, quantity, total: bundle.unitPrice * quantity });
  const icons = [ShieldCheck, Sparkles, Zap, Check];
  return <div><p className="font-[900] tracking-[.2em] text-orange">STRING SHOOTER TOY • AGES 3+</p><h2 className="mb-3 mt-2 text-[clamp(48px,5vw,75px)] font-[700] uppercase leading-[.9] tracking-[-.045em]">{product.name}</h2>{product.reviews > 0 && <Stars rating={product.rating} count={product.reviews} />}<p className="max-w-[570px] text-lg leading-[1.6]">{product.description}</p>
    <div className="my-[25px] grid grid-cols-2 gap-4 max-[560px]:grid-cols-1">{product.benefits.map((benefit, index) => { const Icon = icons[index]; return <div className="flex items-center gap-[11px] [&_p]:m-0 [&_strong]:block [&_strong]:text-xs [&_span]:mt-[3px] [&_span]:block [&_span]:text-xs [&_span]:opacity-70 [&_svg]:text-lime" key={benefit.title}><Icon /><p><strong>{benefit.title}</strong><span>{benefit.text}</span></p></div>; })}</div>
    <p className="inline-flex items-center gap-2 rounded-full bg-[#172b2c] px-[18px] py-[11px] text-xs font-[900] text-lime"><span className="size-2 rounded-full bg-lime shadow-[0_0_12px_#d9ff57]" /> 502 PIECES IN TOTAL STOCK</p>
    <fieldset className="my-[25px] border-0 p-0"><legend className="mb-2.5 text-xs font-[900]">CHOOSE YOUR OPTION</legend>{product.bundles.map((item) => <label key={item.id} className={`my-[9px] grid cursor-pointer grid-cols-[auto_1fr_auto] items-center gap-3 rounded-[15px] border p-4 transition-[background,border-color,transform] duration-200 hover:translate-x-1 ${bundle.id === item.id ? "border-lime bg-[rgba(217,255,87,.07)] text-warm-white shadow-[0_0_0_2px_#d9ff57]" : "border-white/20"}`}><input type="radio" name="bundle" checked={bundle.id === item.id} onChange={() => choose(item.id)} /><span><strong>{item.label}</strong>{item.badge && <small className="mt-1 block font-[900] text-orange">{item.badge}</small>}</span><Price amount={item.unitPrice * item.quantity} compareAt={item.compareAt ? item.compareAt * item.quantity : undefined} /></label>)}</fieldset>
    {bundle.id === "pick-any-two" ? <fieldset className="mb-6 grid grid-cols-2 gap-3 border-0 p-0 max-[560px]:grid-cols-1"><legend className="col-span-full mb-0.5 text-xs font-[900] tracking-[.08em]">PICK BOTH COLOURS</legend>{colors.map((color, index) => <label className="grid gap-2" key={index}><span className="text-xs font-[800] text-[#b8c4cc]">{index === 0 ? "First Ku String" : "Second Ku String"}</span><select className="w-full cursor-pointer rounded-[9px] border border-[#43515d] bg-[#131c24] px-[13px] py-[13px] pr-[38px] font-[800] text-warm-white outline-offset-4 focus-visible:outline-[3px] focus-visible:outline-white" value={color} onChange={(event) => setColors((current) => current.map((value, colorIndex) => colorIndex === index ? event.target.value as KuStringColor : value) as [KuStringColor, KuStringColor])}>{kuStringColors.map((option) => <option key={option} value={option}>{colorLabel(option)}</option>)}</select></label>)}</fieldset> : null}
    <div className="grid grid-cols-[auto_1fr] gap-3.5 max-[560px]:grid-cols-1"><div className="flex items-center rounded-full border border-white/25 max-[560px]:justify-center"><button className="cursor-pointer border-0 bg-transparent p-3 text-inherit outline-offset-4 focus-visible:outline-[3px] focus-visible:outline-white [&_svg]:w-4" aria-label="Decrease quantity" onClick={() => setQuantity(Math.max(bundle.quantity, quantity - bundle.quantity))}><Minus /></button><span>{quantity}</span><button className="cursor-pointer border-0 bg-transparent p-3 text-inherit outline-offset-4 focus-visible:outline-[3px] focus-visible:outline-white [&_svg]:w-4" aria-label="Increase quantity" onClick={() => setQuantity(Math.min(Math.floor(99 / bundle.quantity) * bundle.quantity, quantity + bundle.quantity))}><Plus /></button></div><button className="cursor-pointer rounded-full border-0 bg-lime font-[1000] text-navy outline-offset-4 focus-visible:outline-[3px] focus-visible:outline-white max-[560px]:p-[17px]" onClick={add}>ADD TO CART</button><a className="col-span-full inline-flex min-h-12 w-full items-center justify-center gap-[9px] rounded-full border-2 border-transparent bg-[#25d366] px-5 py-3.5 text-center text-xs font-[1000] leading-[1.2] text-[#052b20] outline-offset-4 transition-[background,transform] duration-[180ms] hover:-translate-y-0.5 hover:bg-[#68e596] focus-visible:outline-[3px] focus-visible:outline-white [&_svg]:size-[18px] [&_svg]:shrink-0 max-[560px]:col-auto max-[560px]:min-h-[52px]" href={whatsappLink} target="_blank" rel="noopener noreferrer" aria-label={`Buy ${product.name} on WhatsApp`}><MessageCircle aria-hidden="true" /> BUY ON WHATSAPP</a></div>
    <p className="sr-only" aria-live="polite">{message}</p><button className="mx-auto mt-[18px] flex items-center gap-[7px] border-0 bg-transparent text-white opacity-80 outline-offset-4 focus-visible:outline-[3px] focus-visible:outline-white"><Share2 /> Share with friends</button>
  </div>;
}
